name: Compile Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout kernel.
         uses: actions/checkout@v4
       - name: Building Kernel.
         run: |
             ls -la
             cd ./kernel_xiaomi_ginkgo/kernel
             chmod 777 build.sh
             ./build.sh

       - name: Uploading ZIP.
         run: |
             cd kernel
             curl -T *.zip https://pixeldrain.com/api/file/ && echo ""
