name: Compile Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout kernel.
         uses: actions/checkout@v4
       - name: Building Kernel.
         run: |
             chmod 777 do_build.sh
             ./do_build.sh

       - name: Uploading ZIP.
         run: |
             cd kernel
             curl -T *.zip https://pixeldrain.com/api/file/ && echo ""
